"""Canonical vocabularies from Rulebook.xlsx sheets 03, 08, 18, 19 and 23.

UNSUPPORTED_CLAIM is a claim/result state, not yet enabled as a finding type:
sheets 03/08 and 19 disagree. No thresholds or rule logic live here.
"""
from enum import StrEnum


class MeasurementType(StrEnum):
    LIVING_AREA = "LIVING_AREA"
    USABLE_AREA = "USABLE_AREA"
    LAND_AREA = "LAND_AREA"
    BUILDING_USABLE_AREA = "BUILDING_USABLE_AREA"
    TAX_AREA = "TAX_AREA"
    ADVERTISED_AREA = "ADVERTISED_AREA"
    OTHER = "OTHER"
    UNKNOWN = "UNKNOWN"


class Scope(StrEnum):
    UNIT = "UNIT"
    BUILDING = "BUILDING"
    OWNERS_ASSOCIATION = "OWNERS_ASSOCIATION"
    PARKING = "PARKING"
    STORAGE = "STORAGE"
    PROJECT = "PROJECT"
    PARCEL = "PARCEL"
    PROPERTY = "PROPERTY"
    BUYER = "BUYER"
    MARKET = "MARKET"
    UNKNOWN = "UNKNOWN"


class FactStatus(StrEnum):
    PROPOSED = "PROPOSED"
    PLANNED = "PLANNED"
    APPROVED = "APPROVED"
    ORDERED = "ORDERED"
    ONGOING = "ONGOING"
    COMPLETED = "COMPLETED"
    CANCELLED = "CANCELLED"
    UNKNOWN = "UNKNOWN"


class AmountType(StrEnum):
    ESTIMATE = "ESTIMATE"
    BUDGET = "BUDGET"
    ACTUAL = "ACTUAL"
    INVOICE = "INVOICE"
    CONTRIBUTION = "CONTRIBUTION"
    RESERVE_BALANCE = "RESERVE_BALANCE"
    RESERVE_WITHDRAWAL = "RESERVE_WITHDRAWAL"
    FEE = "FEE"
    PAYMENT = "PAYMENT"
    FORECAST = "FORECAST"
    CREDIT = "CREDIT"
    ARREARS = "ARREARS"
    SPECIAL_ASSESSMENT = "SPECIAL_ASSESSMENT"
    OTHER = "OTHER"
    UNKNOWN = "UNKNOWN"


class Frequency(StrEnum):
    ONE_TIME = "ONE_TIME"
    MONTHLY = "MONTHLY"
    QUARTERLY = "QUARTERLY"
    ANNUAL = "ANNUAL"
    RECURRING_OTHER = "RECURRING_OTHER"
    UNKNOWN = "UNKNOWN"


class Payer(StrEnum):
    BUYER = "BUYER"
    SELLER = "SELLER"
    OWNERS_ASSOCIATION = "OWNERS_ASSOCIATION"
    TENANT = "TENANT"
    SHARED = "SHARED"
    THIRD_PARTY = "THIRD_PARTY"
    UNKNOWN = "UNKNOWN"


class EvidenceRole(StrEnum):
    SUPPORTS = "SUPPORTS"
    CONTRADICTS = "CONTRADICTS"
    CONTEXT = "CONTEXT"


class DocumentPresence(StrEnum):
    SUPPLIED = "SUPPLIED"
    MISSING = "MISSING"
    UNCLEAR = "UNCLEAR"
    NOT_APPLICABLE = "NOT_APPLICABLE"


class FindingType(StrEnum):
    DOCUMENTED_FACT = "DOCUMENTED_FACT"
    CONFLICT = "CONFLICT"
    MISSING_EVIDENCE = "MISSING_EVIDENCE"
    INFERENCE = "INFERENCE"
    RISK = "RISK"
    POSITIVE_SIGNAL = "POSITIVE_SIGNAL"
    CROSS_DOCUMENT_CONTEXT = "CROSS_DOCUMENT_CONTEXT"


class FindingCategory(StrEnum):
    IDENTITY = "IDENTITY"
    AREA = "AREA"
    PRICE = "PRICE"
    FINANCIAL = "FINANCIAL"
    CONDITION = "CONDITION"
    PROJECT_WORKS = "PROJECT_WORKS"
    ENERGY = "ENERGY"
    LEGAL_TITLE = "LEGAL_TITLE"
    OCCUPANCY_TENANCY = "OCCUPANCY_TENANCY"
    USE_RESTRICTION = "USE_RESTRICTION"
    DOCUMENTATION = "DOCUMENTATION"
    BUYER_FIT = "BUYER_FIT"
    AFFORDABILITY = "AFFORDABILITY"
    RECOMMENDATION = "RECOMMENDATION"
    OTHER = "OTHER"


class Severity(StrEnum):
    CRITICAL = "CRITICAL"
    ATTENTION = "ATTENTION"
    NEEDS_VERIFICATION = "NEEDS_VERIFICATION"
    POSITIVE = "POSITIVE"
    INFORMATIONAL = "INFORMATIONAL"


class FindingStatus(StrEnum):
    OPEN = "OPEN"
    VERIFIED = "VERIFIED"
    UNRESOLVED = "UNRESOLVED"
    INFORMATIONAL = "INFORMATIONAL"


class ReasoningConfidence(StrEnum):
    HIGH = "HIGH"
    MEDIUM = "MEDIUM"
    LOW = "LOW"


class SourceValidationStatus(StrEnum):
    LOCKED_GUARDRAIL = "LOCKED_GUARDRAIL"
    OFFICIAL = "OFFICIAL"
    OFFICIAL_PLUS_PROVISIONAL = "OFFICIAL_PLUS_PROVISIONAL"
    PROVISIONAL_POLICY = "PROVISIONAL_POLICY"
    REFERENCE_TAB_PROVISIONAL = "REFERENCE_TAB_PROVISIONAL"


class EvaluationStatus(StrEnum):
    NOT_TRIGGERED = "NOT_TRIGGERED"
    NEEDS_INPUT = "NEEDS_INPUT"
    EVALUATED = "EVALUATED"
    NOT_APPLICABLE = "NOT_APPLICABLE"


class LayoutStatus(StrEnum):
    CONFORMS = "CONFORMS"
    DIFFERS = "DIFFERS"
    UNKNOWN = "UNKNOWN"


class ClaimVerificationStatus(StrEnum):
    SUPPORTED_CLAIM = "SUPPORTED_CLAIM"
    CONTRADICTED_CLAIM = "CONTRADICTED_CLAIM"
    UNSUPPORTED_CLAIM = "UNSUPPORTED_CLAIM"
    MISSING_UNKNOWN = "MISSING_UNKNOWN"


class PlanningEvidenceStatus(StrEnum):
    DOCUMENTED = "DOCUMENTED"
    MISSING = "MISSING"
    NOT_APPLICABLE = "NOT_APPLICABLE"
    UNKNOWN = "UNKNOWN"


class ConditionEvidenceType(StrEnum):
    CONFIRMED_DEFECT = "CONFIRMED_DEFECT"
    OBSERVATION = "OBSERVATION"
    RECOMMENDATION = "RECOMMENDATION"
    CLAIM = "CLAIM"
    UNKNOWN = "UNKNOWN"


class ResolutionOwner(StrEnum):
    SELLER = "SELLER"
    BUYER = "BUYER"
    LENDER = "LENDER"
    NOTARY = "NOTARY"
    PROPERTY_MANAGER = "PROPERTY_MANAGER"
    AUTHORITY = "AUTHORITY"
    EXPERT = "EXPERT"
    OTHER = "OTHER"


class ResolutionTiming(StrEnum):
    BEFORE_OFFER = "BEFORE_OFFER"
    BEFORE_SIGNING = "BEFORE_SIGNING"
    BEFORE_PAYMENT = "BEFORE_PAYMENT"
    BEFORE_HANDOVER = "BEFORE_HANDOVER"
    POST_PURCHASE = "POST_PURCHASE"
    UNSPECIFIED = "UNSPECIFIED"


class PropertyType(StrEnum):
    APARTMENT = "APARTMENT"
    MAISONETTE = "MAISONETTE"
    HOUSE = "HOUSE"
    OTHER = "OTHER"
    UNKNOWN = "UNKNOWN"


class OccupancyStatus(StrEnum):
    VACANT = "VACANT"
    OWNER_OCCUPIED = "OWNER_OCCUPIED"
    TENANTED = "TENANTED"
    UNKNOWN = "UNKNOWN"


class IntendedUse(StrEnum):
    OWNER_OCCUPIER = "OWNER_OCCUPIER"
    LONG_TERM_RENTAL = "LONG_TERM_RENTAL"
    SHORT_TERM_RENTAL = "SHORT_TERM_RENTAL"
    MIXED = "MIXED"
    OTHER = "OTHER"
    UNKNOWN = "UNKNOWN"


class FinancingStatus(StrEnum):
    APPROVED = "APPROVED"
    CONDITIONALLY_APPROVED = "CONDITIONALLY_APPROVED"
    APPLIED = "APPLIED"
    NOT_APPLIED = "NOT_APPLIED"
    DECLINED = "DECLINED"
    UNKNOWN = "UNKNOWN"


class RiskTolerance(StrEnum):
    LOW = "LOW"
    MEDIUM = "MEDIUM"
    HIGH = "HIGH"
    UNKNOWN = "UNKNOWN"


# Validation vocabulary only; this does not evaluate or implement any B rule.
RULE_RESULTS = {'B01': ('POSITIVE', 'ATTENTION', 'CRITICAL', 'NEEDS_VERIFICATION'),
 'B02': ('POSITIVE', 'ATTENTION', 'CRITICAL', 'NEEDS_VERIFICATION'),
 'B03': ('POSITIVE', 'ATTENTION', 'CRITICAL', 'NEEDS_VERIFICATION'),
 'B04': ('POSITIVE', 'ATTENTION', 'CRITICAL', 'NEEDS_VERIFICATION'),
 'B05': ('POSITIVE', 'ATTENTION', 'CRITICAL', 'NEEDS_VERIFICATION'),
 'B06': ('POSITIVE', 'ATTENTION', 'CRITICAL', 'NEEDS_VERIFICATION'),
 'B07': ('POSITIVE', 'ATTENTION', 'CRITICAL', 'NEEDS_VERIFICATION'),
 'B08': ('POSITIVE', 'ATTENTION', 'CRITICAL', 'NEEDS_VERIFICATION'),
 'B09': ('CHARGE_CONSISTENT', 'CHARGE_CONFLICT', 'STABLE_TREND', 'RISING_TREND', 'CHARGE_UNKNOWN'),
 'B10': ('POSITIVE', 'ATTENTION', 'CRITICAL', 'NEEDS_VERIFICATION'),
 'B11': ('POSITIVE', 'ATTENTION', 'CRITICAL', 'NEEDS_VERIFICATION'),
 'B12': ('POSITIVE', 'ATTENTION', 'CRITICAL', 'NEEDS_VERIFICATION'),
 'B13': ('POSITIVE', 'ATTENTION', 'CRITICAL', 'NEEDS_VERIFICATION'),
 'B14': ('POSITIVE', 'ATTENTION', 'CRITICAL', 'NEEDS_VERIFICATION'),
 'B15': ('POSITIVE', 'ATTENTION', 'CRITICAL', 'NEEDS_VERIFICATION'),
 'B16': ('POSITIVE', 'ATTENTION', 'CRITICAL', 'NEEDS_VERIFICATION'),
 'B17': ('POSITIVE', 'ATTENTION', 'CRITICAL', 'NEEDS_VERIFICATION'),
 'B18': ('POSITIVE', 'ATTENTION', 'CRITICAL', 'NEEDS_VERIFICATION'),
 'B19': ('POSITIVE', 'ATTENTION', 'CRITICAL', 'NEEDS_VERIFICATION'),
 'B20': ('POSITIVE', 'ATTENTION', 'CRITICAL', 'NEEDS_VERIFICATION'),
 'B21': ('POSITIVE', 'ATTENTION', 'CRITICAL', 'NEEDS_VERIFICATION'),
 'B22': ('POSITIVE', 'ATTENTION', 'CRITICAL', 'NEEDS_VERIFICATION'),
 'B23': ('READY', 'READY_WITH_VERIFICATION', 'NOT_DECISION_READY'),
 'B24': ('PROCEED_TO_NEXT_STEP',
         'PROCEED_WITH_CONDITIONS',
         'PAUSE_AND_VERIFY',
         'DO_NOT_PROCEED_AS_STATED'),
 'B25': ('NONE', 'POTENTIAL', 'CONFIRMED'),
 'B26': ('POSITIVE', 'ATTENTION', 'CRITICAL', 'NEEDS_VERIFICATION'),
 'B27': ('POSITIVE', 'ATTENTION', 'CRITICAL', 'NEEDS_VERIFICATION'),
 'B28': ('POSITIVE', 'ATTENTION', 'CRITICAL', 'NEEDS_VERIFICATION'),
 'B29': ('NO_AGE_CONCERN',
         'AGEING_CHECK',
         'RENEWAL_CHECK',
         'CONDITION_ACTION',
         'NEEDS_VERIFICATION'),
 'B30': ('NO_AGE_CONCERN',
         'AGEING_CHECK',
         'RENEWAL_CHECK',
         'CONDITION_ACTION',
         'NEEDS_VERIFICATION'),
 'B31': ('DOCUMENTED_PROJECT_COST',
         'ACTUAL_QUOTE',
         'HISTORICAL_COMPARABLE_WEG_PROJECT',
         'BENCHMARK',
         'NO_ESTIMATE'),
 'B32': ('NOT_TRIGGERED',
         'CHECK_DOCUMENTATION',
         'SPECIALIST_VERIFICATION',
         'CONDITION_CONFIRMED',
         'REMEDIATION_DOCUMENTED'),
 'B33': ('LAYOUT_CONSISTENT', 'LAYOUT_CONFLICT', 'LAYOUT_UNKNOWN', 'LAYOUT_INFERENCE'),
 'B34': ('SUPPORTED_CLAIM', 'CONTRADICTED_CLAIM', 'UNSUPPORTED_CLAIM', 'CLAIM_STATUS_UNKNOWN'),
 'B35': ('EVIDENCE_DOCUMENTED', 'EVIDENCE_MISSING', 'CLAIM_UNSUPPORTED', 'EVIDENCE_CONFLICT'),
 'B36': ('OCCUPANCY_HANDOVER_CONSISTENT',
         'OCCUPANCY_HANDOVER_CONFLICT',
         'OCCUPANCY_HANDOVER_UNKNOWN'),
 'B37': ('RECOMMENDATION_ONLY', 'CONDITION_OBSERVED', 'DEFECT_CONFIRMED', 'CONDITION_UNKNOWN'),
 'B38': ('AUTHORITY_ALIGNED', 'AUTHORITY_CONFLICT', 'AUTHORITY_UNKNOWN')}
